EMBARRASSING SPELLING ERRORS
huntersilvestri/huntersilvestri.github.io pull request #1
Opened 2017-02-07 01:01 UTC by Soleedus

aaaa

2017-02-07 03:20 UTC, Soleedus commented
pls respond

2017-02-08 00:03 UTC, medsouz requested changes
Some suggestions to improve your code quality.

2017-02-08 00:03 UTC, medsouz commented on index.html
> +<title>resumeme</title>
Lacking indentation

2017-02-08 00:03 UTC, medsouz commented on index.html
> +h1 {color:#d23d4e;font-family: Papyrus, fantasy;font-size:600%;}
Formatting errors, missing newlines

2017-02-08 00:03 UTC, medsouz commented on index.html
> +<img src="boi.gif">
Missing image and improper indentation

2017-02-08 00:03 UTC, medsouz commented on index.html
> +<!--stop looking at my code retard-->
Triggered

2017-02-08 00:03 UTC, medsouz commented on index.html
> +	src: url("//soleedus.me/projects/resume/PAPYRUS.TTF") format('truetype');
Do you have the rights to use this font? Please include a license.

2017-02-08 00:05 UTC, medsouz commented
Please squash these commits into one, three is unnecessary.

2017-02-09 02:14 UTC, closed without merging

2017-02-09 02:14 UTC, Soleedus commented
fuck matt he is very stink and Also not very Cool guy!!!!